export type Photo = { src: string; caption: string };

// Real photos live in /public/photos/. The manifest is auto-generated by
// scripts/build-photo-manifest.mjs (runs on predev/prebuild).
export const FALLBACK_POOL: Photo[] = [];

export async function loadPool(): Promise<Photo[]> {
  try {
    const res = await fetch('/photos/manifest.json', { cache: 'no-cache' });
    if (!res.ok) return FALLBACK_POOL;
    const entries = (await res.json()) as { file: string; caption: string }[];
    if (!Array.isArray(entries) || entries.length === 0) return FALLBACK_POOL;
    return entries.map((e) => ({ src: `/photos/${e.file}`, caption: e.caption }));
  } catch {
    return FALLBACK_POOL;
  }
}

export function pickRandom<T>(pool: T[], n: number): T[] {
  const copy = pool.slice();
  // Fisher-Yates
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(n, copy.length));
}
